"""Inicio tabelas

Revision ID: 01962d8b865c
Revises: 
Create Date: 2025-06-06 11:54:57.180389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01962d8b865c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients_records')
    with op.batch_alter_table('supervisor_interns', schema=None) as batch_op:
        batch_op.drop_index('supervisor_id')
        batch_op.drop_index('supervisor_id_2')

    op.drop_table('supervisor_interns')
    op.drop_table('form_question_map')
    op.drop_table('forms_question_answers')
    op.drop_table('forms_answers')
    op.drop_table('forms_questions')
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=14),
               existing_nullable=True)
        batch_op.alter_column('number',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('intern_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('supervisor_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index('cpf')
        batch_op.drop_constraint('patients_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('patients_ibfk_2', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('registration',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('type_user',
               existing_type=mysql.ENUM('admin', 'funcionario'),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('type_user',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'funcionario'),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('registration',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_foreign_key('patients_ibfk_2', 'users', ['supervisor_id'], ['users_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('patients_ibfk_1', 'users', ['intern_id'], ['users_id'], ondelete='SET NULL')
        batch_op.create_index('cpf', ['cpf'], unique=True)
        batch_op.alter_column('supervisor_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('intern_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    op.create_table('forms_questions',
    sa.Column('questions_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('type_of_answer', mysql.ENUM('texto', 'texto_longo', 'numero', 'booleano', 'multipla_escolha', 'opcao_unica', 'data', 'hora', 'escala', 'arquivo'), nullable=True),
    sa.PrimaryKeyConstraint('questions_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('forms_answers',
    sa.Column('answers_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('records_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('forms_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['forms_id'], ['forms.forms_id'], name='forms_answers_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['records_id'], ['patients_records.records_id'], name='forms_answers_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users_id'], name='forms_answers_ibfk_3', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('answers_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('forms_question_answers',
    sa.Column('question_answer_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('answers_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('questions_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answer_text', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['answers_id'], ['forms_answers.answers_id'], name='forms_question_answers_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questions_id'], ['forms_questions.questions_id'], name='forms_question_answers_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_answer_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('form_question_map',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('forms_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('questions_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['forms_id'], ['forms.forms_id'], name='form_question_map_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questions_id'], ['forms_questions.questions_id'], name='form_question_map_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('supervisor_interns',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('supervisor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('intern_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['users.users_id'], name='supervisor_interns_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.users_id'], name='supervisor_interns_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('supervisor_interns', schema=None) as batch_op:
        batch_op.create_index('supervisor_id_2', ['supervisor_id'], unique=False)
        batch_op.create_index('supervisor_id', ['supervisor_id', 'intern_id'], unique=True)

    op.create_table('patients_records',
    sa.Column('records_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patients_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('users_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['patients_id'], ['patients.patients_id'], name='patients_records_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name='patients_records_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('records_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
