"""Criação inicial das tabelas

Revision ID: 78d229ae0d18
Revises: 
Create Date: 2025-06-06 13:57:39.322428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78d229ae0d18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('forms_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('structure_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('forms_id')
    )
    op.create_table('patients',
    sa.Column('patients_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('intern_id', sa.String(length=100), nullable=True),
    sa.Column('supervisor_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('patients_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('registration',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('type_user',
               existing_type=mysql.ENUM('admin', 'funcionario'),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('type_user',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'funcionario'),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('registration',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    op.drop_table('patients')
    op.drop_table('forms')
    # ### end Alembic commands ###
